### ISSUE TITLE
Grid prototype methods require unnecessary binding.

### ISSUE THREAD

**Issue by Hazelfire** [retroverse/hex-redux#21]
Can't work this one out, but when I call grid.neighbours it returns this error message:

> Engine.coffee:123 Bot encounted a runtime error.  TypeError: Cannot read property '0' of undefined
    at grid.neighbours (Grid.coffee:46)
    at Array.map (<anonymous>)
    at RedBot.main (eval at getClass (Brace.coffee:90), <anonymous>:29:38)
    at _Class.module.exports._Class.update (Engine.coffee:121)
    at _Class.module.exports._Class.loop (Engine.coffee:97)

"undefined" appears to be this.state, but I'm not sure how that works...

Here's a bot that can replicate it.

```javascript
return class RedBot extends Bot {
    concat(array1, array2){
        return array1.concat(array2);
    }
    
    rightmost(hex1, hex2){
        if(hex1.x > hex2.x){
        return hex1;
        }
        else{
            return hex2;
        }
    }
                    
    main(grid) {
        // Get all hexs
        let all = grid.all();

        // Filter for those that are red
        let ourTiles = all.filter(grid.is_red);
        
        // Check if we have a red tile
        if(ourTiles.length === 0){
            // Randomly place first tile
            return _.sample(grid.column(0));
        }
        else{
            let neighbors = ourTiles.map(grid.neighbours).reduce(concat, []);
            
            let emptyNeighbors = neighours.filter(grid.is_empty);
            
            let rightMostNeighbour = emptyNeighbours.reduce(rightMost, grid.get(0,0));
            
            return rightMostNeighbour;
        }
    }
}
```

**Comment by retroverse** [comment]
So, I found the related issues:
- The methods, `concat` and `rightmost` are instance variables and therefore have to be called with `this.` i.e `.reduce(this.concat, [])`
- `grid.neighbours` threw an error when called with a hex on the edge of the grid.
- `grid.neighbours` accessed the grid state using the `this` keyword which wasn't bound when used with `Array.map`, this is fixed if you bind it, like so: `arr.map(grid.neighbours.bind(grid))`. This sets the `this` keyword to be the `grid` argument.
- The reduced array of neighbours had duplicates which doesnt really cause an error but seems _wrong_.

Here is a re-written copy of the bot with the issues fixed. _(its also written with standard.js! 😄)_
```javascript
return class RedBot extends Bot {
  concat (array1, array2) {
    return array1.concat(array2)
  }

  main (grid) {
    // Get all hexs
    let all = grid.all()

    // Filter for our colour
    let ourTiles = all.filter((h) => h.value === this.colour)

    // If we don't have any then return a random one in the first column
    if (ourTiles.length === 0) {
      return _.sample(grid.column(0))
    } else {
      // Get all of our tile's neighbours
      let neighbours = ourTiles.map(
        grid.neighbours.bind(grid)
      ).reduce(
        (a, b) => a.concat(b)
      )

      // Remove duplicates by converting to set and back
      neighbours = Array.from(new Set(neighbours))

      // Filter for empty neighbours
      let emptyNeighbours = neighbours.filter(grid.is_empty)

      // Find the right-most neighbour
      let rightMostNeighbour = emptyNeighbours.reduce((a, b) => {
        if (a.x > b.x) {
          return a
        } else {
          return b
        }
      }, grid.get(0, 0))

      // Return it!
      return rightMostNeighbour
    }
  }
}
```

**Comment by Hazelfire** [comment]
I think it's a bit nasty that grid.is_empty, grid.is_blue and grid.is_red does not need binding whereas grid.neighbours does. I understand why it does, but this implementation secret is a bit of a nuisance.

I was wondering if instead of having the grid object passed to the main function, it could somehow be a static global variable? That's the only way I can see we could fix this...

**Comment by retroverse** [comment]
We could potentially have an 'initial' grid. The grid class isn't static because you can create more grids for testing and to test moves and so these methods should be able to target a specific grid. However, we could create a static grid class / set of static methods that specifically target the current grid.

**Comment by Hazelfire** [comment]
Yes! That would be great. One less confusing thing we need to explain to users.

**Comment by retroverse** [comment]
### Resolved
Here is the deal, all of `grid`'s methods are bound to `grid` by default.
So, when you call 
```javascript
[grid.get(0, 0), grid.get(1, 1)]
  .map(grid.neighbours)
```
It is equivalent to
```javascript
[grid.get(0, 0), grid.get(1, 1)]
  .map(grid.neighbours.bind(grid))
```

### Notes
- `grid` methods now cannot be used on other grids without being rebound. This is done very rarely and so is therefore acceptable.
- to clone the grid (and make changes without effecting the original) use the lodash clone (`_.clone`) method and recall the `grid.bindToSelf()` method.
