### ISSUE TITLE
Grid prototypes are bound incorrectly (still)

### ISSUE THREAD

**Issue by retroverse** [retroverse/hex-redux#23]
@Hazelfire has figured out that the grid.bindToSelf function is actually bound and therefore all subsequent clones are also bound. Gonna check this out myself but all help appreciated.

**Comment by retroverse** [comment]
Hey, I personally don't have a chance right now, but @Hazelfire can you test this using your previous method (that you figured this out with) to see if its fixed?

**Comment by Hazelfire** [comment]
Here's a bot that shows the bug

```javascript
return class RedBot extends Bot {
    main(grid) {
        
        let newgrid = grid.take(grid.get(0,0),'red');
        
        console.log("should be red");
        console.log(newgrid.get(0,0));
        console.log("should be red");
        console.log(newgrid.state[0][0]);
        console.log("should be neutral");
        console.log(grid.get(0,0));
        // Get all hexs
        let all = grid.all()

        // Filter for those that are empty
        let empty = all.filter(grid.is_empty)

        // Use lodash to get a random one
        return _.sample(empty)
    }
}
```

newgrid.state and newgrid.get give different results. This issue is still not fixed, I'll look into it

**Comment by Hazelfire** [comment]
Ok, I think I worked it out. I have a strange feeling that newgrid.get is **double bound** (god, I hate JS).

What's happening is when grid.get is called, it's target function is already bound, and adding a this argument to the already bound target function does nothing. So when binding, we need to work out whether it is already bound, and if not, we'll bind it, if it is, then we change it's bound object.

**Comment by Hazelfire** [comment]
Fixed the issue, still not sure how to build it though, npm run build just runs a development server.

**Comment by retroverse** [comment]
If you commit it to master then ill build it for you.

**Comment by retroverse** [comment]
nvm all good
